### ISSUE TITLE
PurgeCSS

### ISSUE THREAD

**Issue by EricPKerr** [tailwindlabs/tailwindcss-playground#1]
Should this include the bare minimum setup for a PurgeCSS implementation?

**Comment by adamwathan** [comment]
Yeah agree, will add this now 👍

**Comment by jethromay** [comment]
In my case the playground demo didn't run on Wndows because it didn't recognize SET_ENV as an internal or external command in package.json. I fixed it by adding cross-env package and prepending cross-env to the scripts commands.

**Comment by adamwathan** [comment]
Added!

https://github.com/tailwindcss/playground/commit/bc0afaaa1ad4b1b84663bb4987554b22b56c27a1
