### ISSUE TITLE
Will this be updated for the lastest releases and changes?

### ISSUE THREAD

**Issue by harshamv** [tailwindlabs/tailwindcss-playground#13]
Will this be updated for the lastest releases and changes?

**Comment by jagreehal** [comment]
@harshamv I've updated in this PR

**Comment by harshamv** [comment]
@jagreehal thanks. will check it out.

**Comment by simonswiss** [comment]
Have just updated to latest and greatest - now works with today's release of Tailwind `v1.7.2` 🎉
