### ISSUE TITLE
Problems getting any of this to work....

### ISSUE THREAD

**Issue by godbrain** [tailwindlabs/tailwindcss-playground#3]
Hi Adam, I've been wanting to try this out for a long time but none of this worked for me. What OS should this work on? Just Mac? First off the clone didn't work without a login so cloning by https worked better. Then I get a message that the package.json doesn't have a license field. Then when I run it I get an error that NODE_ENV is not recognized. This is on Windows. I have not tried it on Ubuntu yet. Was just curious what everyone is running this on to make it work.

Thanks

**Comment by jethromayuk** [comment]
This most definitely works on Windows & Mac. In my case the playground demo didn't run on Wndows because it didn't recognize SET_ENV as an internal or external command in package.json. I fixed it by adding the cross-env package and prepending cross-env to the scripts commands.

For example:

```"serve": "cross-env NODE_ENV=development```

**Comment by adamwathan** [comment]
Good catch, updated the clone instructions to use https and added cross-env for better compatibility.

**Comment by godbrain** [comment]
Thanks!! All working now  :)
